# Generated by Django 5.1.3 on 2024-12-30 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 12, 30, 13, 24, 34, 362765))),
            ],
        ),
    ]
