# Generated by Django 5.1.3 on 2024-12-31 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_apikey_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 31, 5, 8, 30, 585497)),
        ),
    ]
