# Generated by Django 5.1.3 on 2025-01-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datanalysisapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uploadeddata',
            name='user',
        ),
    ]
